import { red, deepPurple, deepOrange, brown } from "@material-ui/core/colors";
export default {
  //* stats *//
  STAT_FEEDBACK: "STAT_FEEDBACK",

  //* constant Arrays as objects *//
  INVITE_STATUSES: {
    PENDING: "PENDING",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED"
  },
  TASK_TYPES: {
    TASK: "TASK",
    BUG: "BUG",
    // IMPROVEMENT: "IMPROVEMENT",
    NEW_FEATURE: "NEW_FEATURE"
  },
  TASK_STATUSES: {
    OPEN: "OPEN",
    IN_DEVELOPMENT: "IN_DEVELOPMENT",
    WAITING_FOR_QA: "WAITING_FOR_QA",
    IN_QA_REVIEW: "IN_QA_REVIEW",
    REJECTED: "REJECTED",
    CLOSED: "CLOSED"
  },
  TASK_PRIORITIES: { MINOR: "MINOR", MAJOR: "MAJOR", CRITICAL: "CRITICAL" },
  TASK_SORT_BY: {
    UPDATED_AT: "UPDATED_AT",
    CREATED_AT: "CREATED_AT"
  },
  TASK_SORT_ORDER: {
    DESC: "DESC",
    ASC: "ASC"
  },
  CARD_STATUSES: {
    STOPPED: "STOPPED",
    ACTIVE: "ACTIVE",
    PAUSED: "PAUSED",
    COMPLETED: "COMPLETED"
  },
  TASKS_COLORS: {
    TASK_PRIORITIES_COLORS: {
      MINOR: "blue",
      MAJOR: "green",
      CRITICAL: red[900]
    },
    TASK_TYPES_COLORS: {
      TASK: "green",
      BUG: red[900],
      NEW_FEATURE: "blue"
    },
    TASK_STATUSES_COLORS: {
      OPEN: "green",
      IN_DEVELOPMENT: deepPurple[600],
      WAITING_FOR_QA: deepOrange[900],
      IN_QA_REVIEW: "blue",
      REJECTED: brown[600],
      CLOSED: brown[600]
    }
  },

  //* sundry *//
  NOT_FOUND: "NOT_FOUND",

  //* search types *//
  SEARCH_EVERYWHERE: "SEARCH_EVERYWHERE",
  SEARCH_USERS: "SEARCH_USERS",
  SEARCH_PROJECTS: "SEARCH_PROJECTS",

  //* balance reducer *//
  BALANCE_SET_BALANCE_LOADED: "BALANCE_SET_BALANCE_LOADED",
  BALANCE_SET_BALANCE: "BALANCE_SET_BALANCE",
  BALANCE_ADD_TO_BALANCE: "BALANCE_ADD_TO_BALANCE",

  //* roadmap reducer *//
  ROADMAP_SET_SEARCH_CARDLESS_FOR: "ROADMAP_SET_SEARCH_CARDLESS_FOR",
  ROADMAP_SET_FILTERED_CARDLESS_TASKS_ORDER:
    "ROADMAP_SET_FILTERED_CARDLESS_TASKS_ORDER",
  ROADMAP_UPDATE_TASK: "ROADMAP_UPDATE_TASK",
  ROADMAP_SET_CARD_TASKS_ORDER: "ROADMAP_SET_CARD_TASKS_ORDER",
  ROADMAP_SET_CARDLESS_TASKS_ORDER: "ROADMAP_SET_CARDLESS_TASKS_ORDER",
  ROADMAP_SET_LOADING_CARDLESS_TASKS: "ROADMAP_SET_LOADING_CARDLESS_TASKS",
  ROADMAP_ADD_TASKS_BY_ID_FROM_ARRAY: "ROADMAP_ADD_TASKS_BY_ID_FROM_ARRAY",
  ROADMAP_SET_ROAD_LIST: "ROADMAP_SET_ROAD_LIST",
  ROADMAP_ADD_ROAD_ITEM: "ROADMAP_ADD_ROAD_ITEM",
  ROADMAP_UPDATE_ROAD_ITEM: "ROADMAP_UPDATE_ROAD_ITEM",
  ROADMAP_DELETE_ROAD_ITEM: "ROADMAP_DELETE_ROAD_ITEM",
  ROADMAP_SET_ROAD_LIST_FETCH_STATUS: "ROADMAP_SET_ROAD_LIST_FETCH_STATUS",
  ROADMAP_SET_CREATING: "ROADMAP_SET_CREATING",
  ROADMAP_SET_ORDER: "ROADMAP_SET_ORDER",
  ROADMAP_ADD_CARD_TO_ROAD: "ROADMAP_ADD_CARD_TO_ROAD",
  ROADMAP_UPDATE_CARD: "ROADMAP_UPDATE_CARD",
  ROADMAP_DELETE_CARD: "ROADMAP_DELETE_CARD",
  ROADMAP_ADD_CARDS_BY_ID: "ROADMAP_ADD_CARDS_BY_ID",
  ROADMAP_SET_CARDS_BY_ID: "ROADMAP_SET_CARDS_BY_ID",
  ROADMAP_SET_ROAD_CARDS_ORDER: "ROADMAP_SET_ROAD_CARDS_ORDER",

  //* sorting orders *//
  ASC: "ASC",
  DESC: "DESC",

  //* global store statuses *//
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  EMAIL_DELIVERED: "EMAIL_DELIVERED",
  EMAIL_NOT_DELIVERED: "EMAIL_NOT_DELIVERED",
  NOT_REQUESTED: "NOT_REQUESTED",
  WAITING: "WAITING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  CONFLICT: "CONFLICT",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  // если пытаемся создать сущность с первичным ключом, который уже сущестует
  CONSTRAINT_VIOLATION: "CONSTRAINT_VIOLATION",

  //* any of reducers *//
  DROP_STATE_ON_UNAUTH: "DROP_STATE_ON_UNAUTH",

  //* notification sundry *//
  NOTIFICATIONS: "NOTIFICATIONS",
  TASK_COMMENTED: "TASK_COMMENTED",
  CHECK_ALL_NOTIFICATIONS: "CHECK_ALL_NOTIFICATIONS",
  CHECKED_ALL_NOTIFICATIONS: "CHECKED_ALL_NOTIFICATIONS",
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",

  //* notificationReducer *//
  NOTIFICATIONS_ADD_NOTIFICATIONS: "NOTIFICATIONS_ADD_NOTIFICATIONS",
  SET_NOTIFICATIONS_LOAD_AFTER: "SET_NOTIFICATIONS_LOAD_AFTER",
  SET_NOTIFICATIONS_CHECKED_AT_TIMESTAMP:
    "SET_NOTIFICATIONS_CHECKED_AT_TIMESTAMP",
  SET_NOTIFICATIONS_SOCKET: "SET_NOTIFICATIONS_SOCKET",
  SET_NOTIFICATIONS_IV: "SET_NOTIFICATIONS_IV",
  SET_NOTIFICATIONS_TOKEN: "SET_NOTIFICATIONS_TOKEN",
  SET_NOTIFICATIONS_NEED_TO_SEND_CHECK_ALL_REQUEST_TO_SOCKET:
    "SET_NOTIFICATIONS_NEED_TO_SEND_CHECK_ALL_REQUEST_TO_SOCKET",

  //* attachmentsReducer *//
  DISARM_ALL_DELETE_ATTACHMENT_BUTTONS: "DISARM_ALL_DELETE_ATTACHMENT_BUTTONS",
  DISARM_ALL_DELETE_ATTACHMENT_BUTTONS_AND_ARM_ONE:
    "DISARM_ALL_DELETE_ATTACHMENT_BUTTONS_AND_ARM_ONE",
  SET_ATTACHMENTS_FETCH_REQUEST_STATUS: "SET_ATTACHMENTS_FETCH_REQUEST_STATUS",
  SET_ATTACHMENTS_LIST: "SET_ATTACHMENTS_LIST",
  DROP_ATTACHMENTS_LIST: "DROP_ATTACHMENTS_LIST",
  ADD_ATTACHMENTS: "ADD_ATTACHMENTS",
  UPDATE_ATTACHMENT: "UPDATE_ATTACHMENT",
  UPDATE_ATTACHMENT_BY_UUID: "UPDATE_ATTACHMENT_BY_UUID",
  DELETE_ATTACHMENT: "DELETE_ATTACHMENT",

  //* userReducer *//
  SET_USER: "SET_USER",
  SET_USER_PROJECT_MANAGER_PROJECTS: "SET_USER_PROJECT_MANAGER_PROJECTS",
  SET_USER_PROJECT_MANAGER_FETCH_REQUEST_STATUS:
    "SET_USER_PROJECT_MANAGER_FETCH_REQUEST_STATUS",

  //* commonReducer *//
  SET_FETCH_LANGUAGES_STATUS: "SET_FETCH_LANGUAGES_STATUS",
  SET_LANGUAGES: "SET_LANGUAGES",
  SET_COMMON_REQUEST_STATUS: "SET_COMMON_REQUEST_STATUS",

  //* authReducer *//
  SET_AUTH_LAST_CONFIRMED_SIGNED_IN_PATHNAME:
    "SET_AUTH_LAST_CONFIRMED_SIGNED_IN_PATHNAME",
  SET_AUTH_LAST_LOGIN_CHECK_PATHNAME: "SET_AUTH_LAST_LOGIN_CHECK_PATHNAME",
  SET_RESET_PASSWORD_STATUS: "SET_RESET_PASSWORD_STATUS",
  SET_REGISTRATION_STATUS: "SET_REGISTRATION_STATUS",
  SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
  SET_ACTIVATION_STATUS: "SET_ACTIVATION_STATUS",
  SET_IS_SIGN_IN: "SET_IS_SIGN_IN",
  SET_REGISTRATION_EMAIL: "SET_REGISTRATION_EMAIL",
  SET_PASSWORD_CHANGE_STATUS_CODE: "SET_PASSWORD_CHANGE_STATUS_CODE",
  RESET_AUTH_STATE: "RESET_AUTH_STATE",
  SET_CHECK_AUTH_REQUEST_STATUS: "SET_CHECK_AUTH_REQUEST_STATUS",



  //* projectReducer *//
  SET_SELECTED_PROJECT_MEMBER: "SET_SELECTED_PROJECT_MEMBER",
  SET_SELECTED_PROJECT_MEMBER_FETCH_STATUS:
    "SET_SELECTED_PROJECT_MEMBER_FETCH_STATUS",
  SET_SELECTED_PROJECT_MEMBER_REQUEST_STATUS:
    "SET_SELECTED_PROJECT_MEMBER_REQUEST_STATUS",
  ADD_PROJECT_MEMBERS: "ADD_PROJECT_MEMBERS",
  FILTER_OUT_PROJECT_MEMBER: "FILTER_OUT_PROJECT_MEMBER",
  SET_PROJECT_MEMBERS: "SET_PROJECT_MEMBERS",
  SET_PROJECT_MEMBERS_FETCH_STATUS: "SET_PROJECT_MEMBERS_FETCH_STATUS",
  SET_PROJECT_UPDATE_STATUS: "SET_PROJECT_UPDATE_STATUS",
  SET_PROJECT_ID: "SET_PROJECT_ID",
  SET_CURRENT_PROJECT_PERMISSIONS: "SET_CURRENT_PROJECT_PERMISSIONS",
  SET_PROJECT_UIID: "SET_PROJECT_UIID",
  SET_PROJECT_INFO: "SET_PROJECT_INFO",
  SET_PROJECT_TASKS: "SET_PROJECT_TASKS",
  SET_PROJECT_SELECTED_TASK_INITIAL_STATE:
    "SET_PROJECT_SELECTED_TASK_INITIAL_STATE",
  SET_PROJECT_SELECTED_TASK_FETCH_STATUS:
    "SET_PROJECT_SELECTED_TASK_FETCH_STATUS",
  SET_PROJECT_FETCH_STATUS: "SET_PROJECT_FETCH_STATUS",
  SET_PROJECT_REQUEST_STATUS: "SET_PROJECT_REQUEST_STATUS",
  SET_PROJECT_DOCUMENTATION_REQUEST_STATUS:
    "SET_PROJECT_DOCUMENTATION_REQUEST_STATUS",
  SET_PROJECT_TASK_SEARCH_PARAMS: "SET_PROJECT_TASK_SEARCH_PARAMS",
  SET_LAST_TASKS: "SET_LAST_TASKS",

  //* helpForSelectedTaskReducer *//
  SET_SELECTED_LINKED_TASK: "SET_SELECTED_LINKED_TASK",
  REMOVE_SELECTED_LINKED_TASK: "REMOVE_SELECTED_LINKED_TASK",
  DISARM_ALL_DELETE_LINKED_TASK_BUTTONS:
    "DISARM_ALL_DELETE_LINKED_TASK_BUTTONS",
  DISARM_ALL_DELETE_LINKED_TASK_BUTTONS_AND_ARM_ONE:
    "DISARM_ALL_DELETE_LINKED_TASK_BUTTONS_AND_ARM_ONE",
  SET_SELECTED_LINKED_TASK_LIST: "SET_SELECTED_LINKED_TASK_LIST",
  SET_CLEAR_ATTACHMENTS: "SET_CLEAR_ATTACHMENTS",
  SET_CLEAR_LINKED_TASKS_LIST: "SET_CLEAR_LINKED_TASKS_LIST",

  //* cacheUsersReducer *//
  ADD_CACHE_USERS_LIST: "ADD_CACHE_USERS_LIST",

  //* uiReducer *//
  CHANGE_DASHBOARD_SIZE: "CHANGE_DASHBOARD_SIZE",
  SET_LINKED_TASKS_LIST_DELETING_ITEM: "SET_LINKED_TASKS_LIST_DELETING_ITEM",
  REMOVE_LINKED_TASKS_LIST_DELETING_ITEM:
    "REMOVE_LINKED_TASKS_LIST_DELETING_ITEM",

  //* favoritesReducer *//
  SET_FAVORITE_LIST: "SET_FAVORITE_LIST",
  ADD_FAVORITE_TO_LIST: "ADD_FAVORITE_TO_LIST",
  REMOVE_FAVORITE_FROM_LIST: "REMOVE_FAVORITE_FROM_LIST",
  SET_FAVORITE_ID_ORDER: "SET_FAVORITE_ID_ORDER",



  //* userSearchReducer *//
  SET_INVITE_TO_PROJECT_OPTION_INVITE_BY_PROJECT_ID:
    "SET_INVITE_TO_PROJECT_OPTION_INVITE_BY_PROJECT_ID",
  SET_USER_PROJECT_MEMBERSHIPS_FETCH_STATUS:
    "SET_USER_PROJECT_MEMBERSHIPS_FETCH_STATUS",
  SET_USER_PROJECT_MEMBERSHIPS: "SET_USER_PROJECT_MEMBERSHIPS",

  SET_SEARCH_FOR_USER: "SET_SEARCH_FOR_USER",

  SET_USER_SEARCH_RESULT: "SET_USER_SEARCH_RESULT",
  SET_USER_SEARCH_RESULT_FETCH_STATUS: "SET_USER_SEARCH_RESULT_FETCH_STATUS",

  SET_FOUND_USER_INFO: "SET_FOUND_USER_INFO",
  SET_FOUND_USER_INFO_FETCH_STATUS: "SET_FOUND_USER_INFO_FETCH_STATUS",
  SET_FOUND_USER_INVITE_TO_PROJECT_OPTIONS:
    "SET_FOUND_USER_INVITE_TO_PROJECT_OPTIONS",
  SET_FOUND_USER_INVITE_TO_PROJECT_OPTIONS_FETCH_STATUS:
    "SET_FOUND_USER_INVITE_TO_PROJECT_OPTIONS_FETCH_STATUS",

  //* invite reducer & actions *//
  SET_INVITE_USER_TO_PROJECT_REQUEST_STATUS:
    "SET_INVITE_USER_TO_PROJECT_REQUEST_STATUS",

  //* projectSearchReducer *//
  SET_SEARCH_FOR_PROJECT: "SET_SEARCH_FOR_PROJECT",

  SET_PROJECT_SEARCH_RESULT: "SET_PROJECT_SEARCH_RESULT",
  SET_PROJECT_SEARCH_RESULT_FETCH_STATUS:
    "SET_PROJECT_SEARCH_RESULT_FETCH_STATUS",

  SET_FOUND_PROJECT_INFO: "SET_FOUND_PROJECT_INFO",
  SET_FOUND_PROJECT_INFO_FETCH_STATUS: "SET_FOUND_PROJECT_INFO_FETCH_STATUS",

  //* regex *//
  REGEX_USERNAME: "[a-z0-9]+",
  REGEX_ALIAS: "[^@;]+",
  REGEX_UIID: "^[a-z0-9_-]+",
  REGEX_EMAIL:
    "[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?",

  //* chat types *//
  TASK: "TASK",
  PROJECT: "PROJECT",

  //* chat sundry *//
  SET_CHAT_CAN_WRITE: "SET_CHAT_CAN_WRITE",
  MESSAGES: "MESSAGES",
  SEND_MESSAGE: "SEND_MESSAGE",
  MESSAGE_ACCEPTED: "MESSAGE_ACCEPTED",
  GET_HISTORY: "GET_HISTORY",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  OK: "OK",
  PING: "PING",
  UNSUBSCRIBED: "UNSUBSCRIBED",
  ERROR: "ERROR",

  //* notifications sundry *//
  ALL_NOTIFICATIONS_CHECKED: "ALL_NOTIFICATIONS_CHECKED",
  UNSUBSCRIBE: "UNSUBSCRIBE",

  //* chatReducer *//
  SET_CHAT_IS_LOADING: "SET_CHAT_IS_LOADING",
  SET_CHAT_LOAD_BEFORE_REQUIRED: "SET_CHAT_LOAD_BEFORE_REQUIRED",
  SET_CHAT_IGNORE_MATCHING_EARLIEST_MESSAGE_TIME_ONLOAD_BEFORE:
    "SET_CHAT_IGNORE_MATCHING_EARLIEST_MESSAGE_TIME_ONLOAD_BEFORE",
  SET_CHAT_SOCKET_TOKEN_NOTIFICATION_TYPE:
    "SET_CHAT_SOCKET_TOKEN_NOTIFICATION_TYPE",
  SET_CHAT_SOCKET_TOKEN_NOTIFICATION_REQUIRED:
    "SET_CHAT_SOCKET_TOKEN_NOTIFICATION_REQUIRED",
  SET_CHAT_LAST_TIME_TOKEN_FETCHED: "SET_CHAT_LAST_TIME_TOKEN_FETCHED",
  CHAT_CONFIRM_MESSAGES_DELIVERY_BY_EXTERNAL_UUIDS:
    "CHAT_CONFIRM_MESSAGES_DELIVERY_BY_EXTERNAL_UUIDS",
  SET_CHAT_TOKEN_REFRESH_REQUIRED: "SET_CHAT_TOKEN_REFRESH_REQUIRED",
  SET_CHAT_RESENDING_UNCONFIRMED_MESSAGES_REQUIRED:
    "SET_CHAT_RESENDING_UNCONFIRMED_MESSAGES_REQUIRED",
  SET_CHAT_TYPE: "SET_CHAT_TYPE",
  SET_CHAT_ID: "SET_CHAT_ID",
  SET_CHAT_EARLIEST_MESSAGE_TIME_ONLOAD_BEFORE:
    "SET_CHAT_EARLIEST_MESSAGE_TIME_ONLOAD_BEFORE",
  SET_CHAT_SOCKET: "SET_CHAT_SOCKET",
  SET_CHAT_TOKEN_REQUEST_STATUS: "SET_CHAT_TOKEN_REQUEST_STATUS",
  SET_CHAT_TOKEN: "SET_CHAT_TOKEN",
  SET_CHAT_IV: "SET_CHAT_IV",
  SET_SENDERS: "SET_SENDERS",
  ADD_SENDER: "ADD_SENDER",
  UPDATE_SENDER: "UPDATE_SENDER",
  ADD_CHAT_MESSAGES_SORT: "ADD_CHAT_MESSAGES_SORT",
  CHAT_RESET: "CHAT_RESET",
  DELETE_CHAT_MESSAGES_BY_EXTERNAL_UUID_LIST:
    "DELETE_CHAT_MESSAGES_BY_EXTERNAL_UUID_LIST",

  //* taskSearchReducer *//
  SET_TASK_SEARCH_FILTER_SEARCH_AFTER: "SET_TASK_SEARCH_FILTER_SEARCH_AFTER",
  SET_TASK_SEARCH_LAST_PROJECT_UI_ID: "SET_TASK_SEARCH_LAST_PROJECT_UI_ID",
  SET_TASK_SEARCH_FETCH_REQUIRED: "SET_TASK_SEARCH_FETCH_REQUIRED",
  SET_TASK_SEARCH_FETCH_STATUS: "SET_TASK_SEARCH_FETCH_STATUS",
  SET_TASK_SEARCH_RESULT: "SET_TASK_SEARCH_RESULT",
  ADD_TASK_SEARCH_RESULT: "ADD_TASK_SEARCH_RESULT",
  RESET_TASK_SEARCH: "RESET_TASK_SEARCH",
  SET_TASK_SEARCH_COUNT_OF_ALL_TASKS: "SET_TASK_SEARCH_COUNT_OF_ALL_TASKS",
  SET_TASK_SEARCH_LOADING_MISSING_TASKS:
    "SET_TASK_SEARCH_LOADING_MISSING_TASKS",

  //* WithFetch.js *//
  FETCH_PROJECT_MEMBER: "FETCH_PROJECT_MEMBER",
  FETCH_FOUND_USER_INVITE_TO_PROJECT_OPTIONS:
    "FETCH_FOUND_USER_INVITE_TO_PROJECT_OPTIONS",
  FETCH_USER_PROJECT_MANAGER_PROJECTS: "FETCH_USER_PROJECT_MANAGER_PROJECTS",
  FETCH_PROJECT: "FETCH_PROJECT",
  FETCH_TASK: "FETCH_TASK",
  FETCH_USER: "FETCH_USER",
  FETCH_USER_PROJECT_MEMBERSHIP: "FETCH_USER_PROJECT_MEMBERSHIP",
  FETCH_PROJECT_MEMBERS: "FETCH_PROJECT_MEMBERS",
  LAZY_FETCH_LANGUAGES: "LAZY_FETCH_LANGUAGES",

  //* localstorage */
  LS_COOKIES_ACCEPTED: "LS_COOKIES_ACCEPTED",

  //* # *//
  HASH_TASKS: "#tasks",
  HASH_EDIT_PROFILE: "#edit-profile"
};
