module.exports = {
  PORT: 8080,
  DEBUG_LOGS: true,
  ERROR_LOGS: true,
  MODE: "development",
  REACT_APP_SERVER_URL: "/",
  REACT_APP_FRONT_URL: "/",
  REACT_APP_FRONT_STATIC_PAGES_PATH: "pages/",
  REACT_APP_API_PREFIX: "clb-web/api",
  REACT_APP_STATISTICS_API_PREFIX: "clb-statistics-web/api",
  REACT_APP_MAX_ATTACHMANT_SIZE_BYTES: 10485760,
  REACT_APP_SITE_KEY_FOR_GRECAPTCHA: "6LcLwL0UAAAAAG9GME11Z02-yuSBEGreGf3wrJJO",
  REACT_APP_ATTACHMENT_ACTIVE_TIME: 120,
  CLOUD_PAYMENTS_PUBLIC_ID: "pk_e176eac16b8948ef49c05d90248ba"
};
